from br.com.grafo.RedeSocial import RedeSocial

rede = RedeSocial()
rede.adicionar_pessoa("Gabriel")
rede.adicionar_pessoa("João")
rede.adicionar_pessoa("Ana")
rede.adicionar_pessoa("Beto")
rede.adicionar_pessoa("Jeferson")
rede.adicionar_pessoa("Nelson")
rede.adicionar_pessoa("Amanda")
rede.adicionar_pessoa("Taynara")
rede.adicionar_pessoa("Jonas")
rede.adicionar_pessoa("Miguel")

rede.adicionar_amizade("Jonas", "João")
rede.adicionar_amizade("João", "Ana")
rede.adicionar_amizade("João", "Beto")
rede.adicionar_amizade("Gabriel", "Beto")
rede.adicionar_amizade("Gabriel", "Amanda")
rede.adicionar_amizade("Gabriel", "Jonas")
rede.adicionar_amizade("Gabriel", "Ana")

rede.adicionar_amizade("Taynara", "João")
rede.adicionar_amizade("Taynara", "Amanda")
rede.adicionar_amizade("Taynara", "Gabriel")
rede.adicionar_amizade("Taynara", "Jonas")
rede.adicionar_amizade("Taynara", "Jeferson")
rede.adicionar_amizade("Jeferson", "Beto")
rede.adicionar_amizade("Miguel", "Nelson")

print(rede.mais_popular())
rede.visualizar_grafo()
